# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: antlike Tech
title: antlike Tech
email: mail@gitm8.com
copyright:
  year:             2017
  name:             GitM8

description: > # this means to ignore newlines until "baseurl:"
  My personal blog and project space. From time to time writing articles about tech stuff
  (mostly node.js and javascript). You can also find the slides from my meetup talks as well
  as documentation for my open source projects.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /blog/:title.html
url: "http://www.antlike.tech"
# url: "http://localhost:4000"
excerpt_separator: <!--more-->

author:
  twitter: gitm8
  github: thegitm8
  email: mail@gitm8.com

twitter_username: gitm8
github_username:  thegitm8

nav:
  - name: "Projects"
    url: "/projects"
  - name: "Slides"
    url: "/slides"
  - name: "Blog"
    url: "/blog"
  - name: "About"
    url: "/about"


paginate: 3
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
