name: antlike tech
title: antlike Tech
email: website@antlike.tech
description: >
  Robert Docters personal blog and project space. Javascript and Node.js articles and tutorials, local meetup slides and videos as well
  as documentation for my open source projects.
baseurl: ""
permalink: /blog/:title.html
url: "http://www.antlike.tech"

author:
  name: Robert Docter
  image: /assets/images/robert_docter_antlike_tech_portrait.jpg
  twitter: gitm8
  github: thegitm8
  email: website@antlike.tech

# Navigation
nav:
  - name: "Projects"
    url: "/projects"
  - name: "Slides"
    url: "/slides"
  - name: "Blog"
    url: "/blog"
  - name: "About"
    url: "/about"

# Blog settings
paginate: 3
paginate_path: /blog/page:num/

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
